version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - yarn install --lock-file

  build:
    commands:
      - yarn build

  post_build:
    commands:
      - aws s3 sync --delete ./dist s3://task-manager-private
      - aws cloudfront create-invalidation --distribution-id E3RLJARJLUE5ID --paths /index.html
